Выполнил задание "Камень судьбы"
htmlacademy-yii/1583561-task-force-1 pull request #2
Opened 2020-09-06 18:37 UTC by Dijkstra-ru

2020-09-07 06:07 UTC, nikserg requested changes
Очень хорошо. Понимание кода отличное, есть несколько косметических замечаний.

2020-09-07 06:07 UTC, nikserg commented on Readme.md
> +$ composer dump-autoload
Для запуска "с нуля" нужно писать `composer install`.
`composer dump-autoload` не устанавливает пакетов, а перегенерирует файл автозагрузки. Это нужно делать в единственном случае: когда поменялись неймспейсы в блоке psr4.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +  const STATUS_NEW = 'status_new'; // Новое - Задание опубликовано, исполнитель ещё не найден
Это никак не влияет на функциональность, но я бы дал константам значения без префикса `status_`, `action_` и так далее. То, что это status или action следует из названия атрибута, в котором это значение написано.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +  private $readableNamesMap = [
Лайфхак: можно сделать `const READABLE_NAMES_MAP`. Тогда и геттер не нужен.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +  private $readableNamesMap = [
И еще один момент: не нужно мешать в один массив константы разных типов. У них могут совпадать значения. Например, STATUS_NEW = 'new' и ROLE_NEW_USER = 'new'. 
Либо сделать `READABLE_NAMES_MAP = ['actions' => [..], 'statuses' => [...]];`, либо сделать `STATUS_NAMES`, `ACTION_NAMES`.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +  public function getNextStatus($action) {
Немного забегаешь вперед, да? В рамках этого задания были просто интерфейсы, без реализации. Ну да ладно

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +          return self::STATUS_CANCELED;
Если я правильно помню следующее задание, там надо было массивы возвращать. Давай тогда отложим проверку тела методов до проверки следующего задания, хочу еще само задание почитать.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +  public function __construct($contractorId, $clientId) {
Напиши комментарий для конструктора, хотя бы просто с типами аргументов.

2020-09-07 06:07 UTC, nikserg commented on src/Task.php
> +class Task {
Нужно писать комментарии к классам и к методам. Пару слов о том, что это за сущность, зачем она нужна. И у методов соответственно аннотацию к типам параметров и краткое описание функции.

2020-09-07 11:55 UTC, Dijkstra-ru commented on src/Task.php
> +  const STATUS_NEW = 'status_new'; // Новое - Задание опубликовано, исполнитель ещё не найден
Я хотел бы выступить в защиту префиксов: они спасают от ошибки, когда вместо класса действия передаётся класс статуса (или наоборот). Кейс: пользователь класса ошибается и вызывает функцию `getNextStatus` с (гипотетическим) аргументом `ACTION_NEW` вместо `STATUS_NEW`. Если использовать префиксы, то такое поведение вызовет ошибку времени выполнения. К сожалению, в PHP нет `enum`'ов и невозможно вызвать ошибку времени разбора программы. Поэтому, как мне кажется, с точки зрения дальнейшего расширения класса было бы целесообразно оставить префиксы. Как вариант могу предложить заменить строки на непересекающиеся числа.

2020-09-07 11:58 UTC, Dijkstra-ru commented on src/Task.php
> +  private $readableNamesMap = [
В том числе по этому поводу я и использую префиксы.
В данном случае использование одного метода является требованием задания -- карта явно указана в единственном числе.
> класс имеет методы для возврата «карты» статусов и действий. Карта — это ассоциативный массив, где ключ — внутреннее имя, а значение — названия статуса/действия на русском.

Впрочем, я легко готов поступиться заданием и исправить этот недочёт.

2020-09-07 12:26 UTC, nikserg requested changes

2020-09-07 12:26 UTC, nikserg commented on src/Task.php
> +  const STATUS_NEW = 'status_new'; // Новое - Задание опубликовано, исполнитель ещё не найден
Думаю, в случае правильного именования атрибутов и наличии комментариев такие ошибки практически исключены. Но ты можешь оставить префиксы, это больше дело вкуса.

2020-09-07 12:26 UTC, nikserg commented on src/Task.php
> +  private $readableNamesMap = [
Обычно студенты реализуют две карты: одну для действий, другую для значений. Да и вообще такой подход наиболее распространен: на каждый атрибут своя карта имен. 
Твой подход тоже будет работать, так что можно оставить, если будешь оставлять префиксы значений констант.

2020-09-07 12:47 UTC, Dijkstra-ru commented on Readme.md
> +$ composer dump-autoload
Исправил

2020-09-07 12:54 UTC, Dijkstra-ru commented on src/Task.php
> +  const STATUS_NEW = 'status_new'; // Новое - Задание опубликовано, исполнитель ещё не найден
Всё-таки оставил с префиксами

2020-09-07 13:04 UTC, Dijkstra-ru commented on src/Task.php
> +  private $readableNamesMap = [
Создал отдельные карты для действий и значений, но на всякий случай оставил старый метод, возвращающий свалку. Просто для совместимости и из упрямства.

2020-09-07 13:05 UTC, Dijkstra-ru commented on src/Task.php
> +  public function getNextStatus($action) {
Я так понял задание, кажется, я выполнил заодно и следующее

2020-09-07 13:07 UTC, Dijkstra-ru commented on src/Task.php
> +          return self::STATUS_CANCELED;
На всякий случай вернул массивы

2020-09-07 13:07 UTC, Dijkstra-ru commented on src/Task.php
> +  public function __construct($contractorId, $clientId) {
Закомментировал все публичные методы и конструктор с помощью PHPDOC

2020-09-07 13:07 UTC, Dijkstra-ru commented on src/Task.php
> +class Task {
Закомментировал все публичные методы и конструктор с помощью PHPDOC

2020-09-08 13:51 UTC, nikserg requested changes
Еще немного доработать комментарии.

2020-09-08 13:51 UTC, nikserg commented on src/Task.php
> +  public function __construct($contractorId, $clientId) {
Хорошо, что в комментарии есть пояснение сути аргумента ("Идентификатор исполнителя"), но стоит еще добавить тип переменной. Чтобы получилось 
`@param int $contractorId Идентификатор исполнителя`

2020-09-08 13:52 UTC, nikserg commented on src/Task.php
> +  private $readableNamesMap = [
Можно тогда оставить только твой подход. Не принципиально делать единую карту, главное, чтобы тебе было удобно со своим кодом работать.

2020-09-08 14:20 UTC, Dijkstra-ru commented on src/Task.php
> +  public function __construct($contractorId, $clientId) {
Добавил типы переменных в PHPDOC

2020-09-08 14:20 UTC, Dijkstra-ru commented on src/Task.php
> +class Task {
Добавил комментарий к классу

2020-09-08 15:09 UTC, merged